### ISSUE TITLE
Password issue

### ISSUE THREAD

**Issue by Zorta75** [crypto-com/chain-desktop-wallet#1068]
Hi,

I have my recovery phrase, but i don't remember the password that locked my wallet client on my desktop.

How can I force the wallet desktop to reset this password and recover my wallet with my recovery phrase please ?

I can still use defi wallet app on my mobile for the moment, but the client desktop notice me the self destruct of my account shoud I make 5  errors again.

Thanks,

**Comment by crypto-matto** [comment]
Hi @Zorta75, great that you have your recovery phrase. Due to the fact that all recovery phrases inside Desktop Wallet are encrypted & we don't store the password itself, we're not able to reset the password without removing all the existing wallets. Therefore, technically, reseting the password on Desktop Wallet meaning a self-destruct action on you wallets & you'll have to reimport them one by one. 

You may go to `Settings` => `Clear Storage` to reset your password & recover your wallets. 
Just a reminder like the description under `Clear Storage`: 
``` Once you clear the storage, you will lose access to all your wallets. The only way to regain wallet access is by restoring wallet mnemonic phrase.```

**Comment by Zorta75** [comment]
Hi,

I would like to be sure, when I enter several times the bad password on the
desktop wallet the only consequence is the self destruct of the wallet
acces from the computer ?
And then the desktop wallet will propose me to restore my wallet with my
recovery phrase ?

The term "self destruct wallet" scares me. I don't want to lose my wallet
definitively.

thanks,


Le mar. 10 mai 2022 à 05:44, crypto-matto ***@***.***> a
écrit :
