### ISSUE TITLE
Feature: WalletConnect and/or DeFiConnect support

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain-desktop-wallet#1095]
**Is your feature request related to a problem? Please describe.**
The desktop wallet is missing here:

<img width="558" alt="walletconnect" src="https://user-images.githubusercontent.com/2410580/169259136-e99cb953-940f-4931-aafd-83f39d468767.png">

**Describe the solution you'd like**
I guess there are several things needed:

1. handling "applinks" -- the "desktop" support is done via a registered app link for each wallet, e.g. "ledgerlive://..."
2. handling the walletconnect requests
3. updating the walletconnect modal (in [this repo](https://github.com/WalletConnect/walletconnect-monorepo)?)

**Describe alternatives you've considered**
n/a -- maybe copy-pasting the connection string?

**Additional context**
to be able to use the desktop wallet on https://cronos.org/nft-faucet

**Comment by XinyuCRO** [comment]
One thing we can do to use the NFT faucet in DAppBrowser is we can remove the install MetaMask checking in the faucet, and make the faucet connectable when there is no MetaMask installed. 

<img width="446" alt="image" src="https://user-images.githubusercontent.com/91446598/169994504-f42fa0b2-acab-4671-8126-017f332e3fc7.png">

Because MetaMask connector is kind of like a generic provider, many wallets are connectable via it, eg. mobile wallets like Defi wallet, imToken, and Desktop Wallet, adding the check will block many of the wallets which can connect with the generic provider.

The NFT faucet will be usable once the check is removed and #1032 is merged

And yeah, we should definitely support WalletConnect

**Comment by crypto-matto** [comment]
> Because MetaMask connector is kind of like a generic provider, many wallets are connectable via it, eg. mobile wallets like Defi wallet, imToken, and Desktop Wallet, adding the check will block many of the wallets which can connect with the generic provider.

Well said. Desktop Wallet shall be able to support NFT faucet immediately when the checking block is removed.
 
We’ve scheduled & looking forward to support WalletConnect in late-June / July.
