### ISSUE TITLE
a big problem with ledger

### ISSUE THREAD

**Issue by spreadcontact** [crypto-com/chain-desktop-wallet#1269]
I staked my cronos via ledger.
I have tried to withdraw my cronos, but the app says that the wallet address does not coincide with the one entered and it is not possible to recover them.
how can I do?

**Comment by crypto-matto** [comment]
Hi @spreadcontact, we noticed that there're this issue happening for some users on Windows. Before we launch a fix patch, you may tried several options for the time being:

1. Downgrade to [1.2.0](https://github.com/crypto-com/chain-desktop-wallet/releases/tag/v1.2.0)
2. Import your Ledger address again
- Go to “Create Wallet”
- Check “Want to create with hardware wallet?”
- Input “Index” & “Standard” accordingly with the value of his original address
Your “Index” & “Standard” can be found in the Wallet List.

**Comment by crypto-matto** [comment]
Hi @spreadcontact, we discovered that it's due to the Wallet-Lock feature, and we're fixing this issue on later release 1.3.4 soon. Before that, avoid using the Wallet-Lock feature. Please make sure you're up to date with the release. But I'm sorry that you may need to re-import the Ledger wallet once again. 

Import your Ledger address again:
- Go to “Create Wallet”
- Check “Want to create with hardware wallet?”
- Input “Index” & “Standard” accordingly with the value of his original address
Your “Index” & “Standard” can be found in the Wallet List.

**Comment by crypto-matto** [comment]
Hi @spreadcontact, please download our latest v1.3.5 release to eliminate the problem. 

While v1.3.4 fixed the issue, I’m afraid you will need to reimport their ledger wallet once again, in order to back to normal usage:

1. Go to “Create Wallet”
2. Check “Want to create with hardware wallet?”
3. Input “Index” & “Standard” accordingly with the value of your original address

You could locate “Index” & “Standard” at Wallet List page.
