### ISSUE TITLE
Problem : Missing mnemonic phrase encryption and decryption flow with its relation with the app password

### ISSUE THREAD

**Issue by crypto-eddy** [crypto-com/chain-desktop-wallet#35]
### Current state

Currently, mnemonic phrases are stored in plain text format, but the goal is to have them saved after being encrypted.

### Objectives

- We should be able to save the mnemonic phrase encrypted after import/restore or new wallet creation

- When the user wants to do a transaction, we should be able to decrypt the encrypted mnemonic and extract the key from the mnemonic for signing purposes.

- The phrase should normally be encrypted with the user set password as the encryption key so that only the user or owner of the password can decrypt it and sign transactions

### Outcome

At the end of this task, we should have the implementation of the 3 main steps or functions :

- Storing passwords securely, since these passwords will later be used as encryption keys

- Using that stored password to encrypt the mnemonic phrase, here the previously stored password is used as the encryption key. We'd only store the encrypted mnemonic phrase.

- And finally decrypting the previously-stored phrase with the password ( which was used as the encryption key ) and use the phrase to sign transactions when needed. 

### Note

This task is not UI related, it's mostly logic behind the storage of sensitive data, the encryption and decryption of phrases.

**Comment by DanielBoba** [comment]
Version v0.1.2
Hello Again guys, so, long story. but the only way to recover my CRO is from the windows desktop wallet. after a few months of use and android wallet (lose phone, lose keys) there is the only way. now i`m trying to move to a new wallet in windows and it asking me a passport for dercypt wallet. I tried every password that i use in my life and app is not working. I thing this is not a problem of the 12 worlds and in some way can be fixed. I´m desperated. Can we compile a version of the app whi avoid the password ? this worked before. I don´t want to update tje version because I feel feer to app ask again to import and again i´don´t have the 12 words ! but the app is opening on this version. how can it posible ? words shouls taken from somewhere!
Any help will be appreciate.

Sorry for help this here but i don´t have your emails
