### ISSUE TITLE
chain-desktop-wallet-setup-0.1.2.exe SHA512 Checksum invalid

### ISSUE THREAD

**Issue by subimpact** [crypto-com/chain-desktop-wallet#370]
version: 0.1.2
files:
  - url: chain-desktop-wallet-setup-0.1.2.exe
    sha512: rodWaX/YwzMEPcTPqZXknhhULRciLvlSAHvI8Jb7Zw83++E5BXCSHuk9Y1wiDieUYaZBfDTtOZoQvhGnu6Cujw==
    size: 141688852
path: chain-desktop-wallet-setup-0.1.2.exe
sha512: rodWaX/YwzMEPcTPqZXknhhULRciLvlSAHvI8Jb7Zw83++E5BXCSHuk9Y1wiDieUYaZBfDTtOZoQvhGnu6Cujw==
releaseDate: '2021-03-30T07:43:00.928Z'

SHA512 hash of chain-desktop-wallet-setup-0.1.2.exe:
ae8756697fd8c333043dc4cfa995e49e18542d17222ef952007bc8f096fb670f37fbe1390570921ee93d635c220e279461a6417c34ed399a10be11a7bba0ae8f

**Comment by sinN89** [comment]
I'm getting

Algorithm : SHA256
Hash      : 5AABCB7BBD57B5481DA438FDBD0CC4EE18FE3ED943D227742ABB4608BD734E55
Path      : C:\Users\xxx\Downloads\chain-desktop-wallet-setup-0.1.2.exe

**Comment by sinN89** [comment]
Same here :)

**Comment by sinN89** [comment]
Would it be an idea to display it in hex too ? Many of us just using cerutil.exe binary or Get-FileHash PS cmdlet which returns hex by default

**Comment by eddycpc** [comment]
We can possibly look into that capability to show them in hex if that's possible, this is because the build tools we use tend to do an implicit conversion to base 64 for release hashes.

You can be using online tool to convert a hex sha512 to base 64 like this one here https://base64.guru/converter/encode/hex

You can see how `ae8756697fd8c333043dc4cfa995e49e18542d17222ef952007bc8f096fb670f37fbe1390570921ee93d635c220e279461a6417c34ed399a10be11a7bba0ae8f` matches `rodWaX/YwzMEPcTPqZXknhhULRciLvlSAHvI8Jb7Zw83++E5BXCSHuk9Y1wiDieUYaZBfDTtOZoQvhGnu6Cujw==

`
<img width="1512" alt="Screen Shot 2021-03-31 at 10 34 39 AM" src="https://user-images.githubusercontent.com/73159521/113107532-b8a4c100-920c-11eb-8e49-768d95b8f735.png">

**Comment by subimpact** [comment]
thanks ! will close this issue
