### ISSUE TITLE
Is this wallet safe for staking?

### ISSUE THREAD

**Issue by GiuseppeDM98** [crypto-com/chain-desktop-wallet#402]
Hi, as written in the Readme file, this wallet is in beta, my question is, can I move my CROs and stake them in a "safe" way or do I risk losing everything because maybe there is a bug or similar?
Thanks in advance!

**Comment by Techboy** [comment]
Please ask questions in https://www.reddit.com/r/Crypto_com/ as this section is for posting issues with the app, it isn't a chat forum.

But to answer your question - the app has been used on the Testnet (test blockchain) for months and on the mainnet (live blockchain) since 25th March. I haven't seen any reports of any issues. I have been using it for a week without any issues and have transacted ~30 times.

I will write an article on it soon, feel free to follow me on Medium, you can see one of my articles here https://techboy.medium.com/the-essential-guide-to-the-mco-visa-debit-card-from-crypto-com-61d7b2f358c9

**Comment by Techboy** [comment]
Please ask questions in https://www.reddit.com/r/Crypto_com/ as this section is for posting issues with the app, it isn't a chat forum.

But to answer your question - the app has been used on the Testnet (test blockchain) for months and on the mainnet (live blockchain) since 25th March. I haven't seen any reports of any issues. I have been using it for a week without any issues and have transacted ~30 times.

I will write an article on it soon, in the mean time, please follow me on Medium, you can see one of my articles here https://techboy.medium.com/the-essential-guide-to-the-mco-visa-debit-card-from-crypto-com-61d7b2f358c9

**Comment by GiuseppeDM98** [comment]
Ok thanks, i will surely follow you on Medium!
