### ISSUE TITLE
Claim & Delegate rewards in 1 action

### ISSUE THREAD

**Issue by sinN89** [crypto-com/chain-desktop-wallet#569]
If I'm correct, on the Android App, it's possible to claim rewards et delegate them again in 1 action button.
Would it be possible to add this in the desktop wallet ?

Thanks,

**Comment by crypto-matto** [comment]
Hi @sinN89 . Just tried on the DeFi Wallet & I believe both DeFi Wallet Mobile App & Desktop Wallet requires 4 actions.
1. Tap `Claim Rewards`
2. Choose between `Claim to Wallet` and `Claim to Restake`
3. Tap `Confirm Claim` in Confirmation
4. Insert your `App Passcode` (which could be quick if Face ID is enabled)

On Desktop Wallet, it requires 4 actions as well.
1. Click `Withdraw Reward`
2. Insert your `App Passcode`
3. Click `Continue` of Success Modal
4. Click `Confirm` in Confirmation 

Just to let you know that safety & security is our outmost concern. Both the insert of `App Passcode` & Confirmation are measures to secure your assets. That's why we include these actions in all of our transactions. 
But I believe we may enhance to skip the `Continue` click in Success Modal to speed up the process. Thanks for your suggestion.

**Comment by sinN89** [comment]
Hi,

I've not used the Mobile App, but as you say, there is the option "Claim to Restake" which I imagine, immediately delegate the claimed amount.

On the other side, on the Desktop App, I have to "Claim Rewoards". it's then in my balance. Then, I've to "Delegate", which is one more step.

It seems the Mobile App does it in 1 step instead of 2. Or am I missing something ?

**Comment by crypto-matto** [comment]
> Hi,
> 
> I've not used the Mobile App, but as you say, there is the option "Claim to Restake" which I imagine, immediately delegate the claimed amount.
> 
> On the other side, on the Desktop App, I have to "Claim Rewards". it's then in my balance. Then, I've to "Delegate", which is one more step.
> 
> It seems the Mobile App does it in 1 step instead of 2. Or am I missing something ?

I see your point, my mistake. 
It's a good to add feature with a `Restake reward` next to `Withdraw reward`.
Will take your suggestion into consideration. Thanks.

**Comment by sinN89** [comment]
Super, thanks a lot !

**Comment by crypto-matto** [comment]
## Propose Solution
Step 1: We broadcast a withdraw reward transaction
Step 2: We use the reward amount and put it in delegation

## Possible Scenarios
1. Both withdraw rewards & delegate rewards running smooth
    - Just show success popup, everything works fine

2. Withdraw rewards fail
    - Just show error popup and stops right Step 1
3.  Withdraw rewards broadcast succeeded without timeout, but delegate rewards timeout
    - We may still show success popup, with a message saying "probably timeout & will include in later blocks". Similar to our existing The transaction timed out but it will be included in the subsequent blocks
4. Withdraw rewards broadcast succeeded without timeout, but delegate rewards failed
    - We may still show success popup, with a message "We only withdraw your rewards but failed to restake rewards"
5. Withdraw rewards broadcast succeeded with timeout
    - Same handle with Scenario 4. We may still show success popup, with a message "We only withdraw your rewards but failed to restake rewards"
